version: '2.4'

services:
  resourcedb:
    image: postgres:latest
    environment:
      POSTGRES_USER: resourcer
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: resourcedb
    ports:
      - "7000:5432"
    volumes:
      - resourcedb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      resourcedb:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://resourcer:pa55word@resourcedb:5432/resourcedb?sslmode=disable", "up"]

volumes:
  resourcedb_data: